### ISSUE TITLE
The plugin does not seem to work on QGIS 3.20.0

### ISSUE THREAD

**Issue by Joonalai** [UnfoldedInc/qgis-plugin#57]
**Describe the bug**
Export map produces the following error:
```
Process ended: Exception occurred during data extraction: /home/<user>/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Unfolded/resources/tmp7dgpcg7l/Newscratchlayer.csv
```
And log output:

<details>

23.06.2021 13:01:47 - [ERROR  ] - base_config_creator_task.py:107 : Process ended
Traceback (most recent call last):
  File "/home/<user>/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Unfolded/core/processing/base_config_creator_task.py", line 105, in finished
    raise self.exception
  File "/home/<user>/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Unfolded/core/processing/layer2dataset.py", line 63, in run
    self.result_dataset = self._convert_to_dataset()
  File "/home/<user>/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Unfolded/core/processing/layer2dataset.py", line 81, in _convert_to_dataset
    source, all_data = self._extract_all_data()
  File "/home/<user>/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Unfolded/core/processing/layer2dataset.py", line 161, in _extract_all_data
    output_file = self._save_layer_to_file(self.layer, self.output_directory)
  File "/home/<user>/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Unfolded/core/processing/layer2dataset.py", line 213, in _save_layer_to_file
    raise ProcessInterruptedException(tr('Process ended'),
Unfolded.core.exceptions.ProcessInterruptedException: Process ended
23.06.2021 13:01:47 - [WARNING] - config_creator.py:233 : Task dd744b63-f595-4a21-b760-3e56cc65c1d6 terminated

</details>

**To Reproduce**
1. Create new scratch layer with any kind of geometry
2. Create at least one features
3. Export map

**Expected behavior**
Export map should export a config zip

**Desktop (please complete the following information):**
 - Plugin: 1.0.1
 - QGIS: 3.20.0
 - Python: 3.9.5
 - OS: Arch Linux

**Comment by Joonalai** [comment]
This line causes the problem:
https://github.com/UnfoldedInc/qgis-plugin/blob/04d36c15aea1699a08317074231a9b7de481b7ff/Unfolded/core/processing/layer2dataset.py#L209
